"""Model run primitive."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import Field

from .base import EvidencePrimitive


class ModelRun(EvidencePrimitive):
    """Derived result generated by a model, algorithm, or simulation."""

    schema_id: Literal["athian.agevidence.model_run.v1"] = "athian.agevidence.model_run.v1"
    primitive_type: Literal["ModelRun"] = "ModelRun"
    model_id: str
    model_version: str
    implementation_digest: str | None = None
    input_commitments: list[str] = Field(default_factory=list)
    parameters: dict[str, Any] = Field(default_factory=dict)
    execution_environment: dict[str, Any] = Field(default_factory=dict)
    started_at: str | None = None
    completed_at: str | None = None
    outputs: list[Any] = Field(default_factory=list)
    verification: dict[str, Any] = Field(default_factory=dict)

    # Compatibility fields for the older model_execution.v1 receipt payload.
    inputs: list[Any] = Field(default_factory=list)
    executed_at: str | None = None
    weights_digest: str | None = None
    adapter_id: str | None = None
    adapter_digest: str | None = None
    model_license: str | None = None
    runtime: str | None = None
    generation_config: dict[str, Any] = Field(default_factory=dict)
    system_prompt_digest: str | None = None
    retrieval_corpus_digest: str | None = None
    source_document_commitments: list[str] = Field(default_factory=list)
    normalized_output_digest: str | None = None
    policy_version: str | None = None
    issuer: str | None = None
    signer: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
    limitations: list[str] = Field(default_factory=list)

    def to_model_execution_payload(self) -> dict[str, Any]:
        """Project this primitive into the existing Rust model execution schema."""

        return {
            "base_model_id": self.model_id,
            "model_version": self.model_version,
            "weights_digest": self.weights_digest or self.implementation_digest,
            "adapter_id": self.adapter_id,
            "adapter_digest": self.adapter_digest,
            "model_license": self.model_license,
            "runtime": self.runtime or self.execution_environment.get("runtime"),
            "generation_config": self.generation_config or self.parameters,
            "system_prompt_digest": self.system_prompt_digest,
            "retrieval_corpus_digest": self.retrieval_corpus_digest,
            "source_document_commitments": self.source_document_commitments or self.input_commitments,
            "normalized_output_digest": self.normalized_output_digest or self.verification.get("normalized_output_digest"),
            "policy_version": self.policy_version or self.verification.get("policy_version"),
            "limitations": self.limitations,
            "execution_timestamp": self.executed_at or self.completed_at or self.started_at,
            "issuer": self.issuer or self.verification.get("issuer"),
            "signer": self.signer or self.verification.get("signer"),
            "inputs": self.inputs or self.input_commitments,
            "outputs": self.outputs,
        }

    def to_legacy_model_execution_payload(self) -> dict[str, Any]:
        """Return the existing model_execution.v1 projection explicitly."""

        return {key: value for key, value in self.to_model_execution_payload().items() if value is not None}

    def to_payload(self) -> dict[str, Any]:
        """Return the neutral model_run.v1 primitive payload."""

        payload = {
            "schema_id": self.schema_id,
            "primitive_type": self.primitive_type,
            "model_id": self.model_id,
            "model_version": self.model_version,
            "implementation_digest": self.implementation_digest or self.weights_digest,
            "input_commitments": self.input_commitments or self.source_document_commitments or _string_inputs(self.inputs),
            "parameters": self.parameters or self.generation_config,
            "execution_environment": self.execution_environment or _runtime_environment(self.runtime),
            "started_at": self.started_at or self.executed_at,
            "completed_at": self.completed_at or self.executed_at,
            "outputs": self.outputs,
            "limitations": self.limitations,
            "verification": self.verification or _verification_metadata(self),
            "metadata": self.metadata,
        }
        return {key: value for key, value in payload.items() if value is not None}


def _string_inputs(inputs: list[Any]) -> list[str]:
    return [item for item in inputs if isinstance(item, str)]


def _runtime_environment(runtime: str | None) -> dict[str, Any]:
    return {"runtime": runtime} if runtime else {}


def _verification_metadata(model_run: ModelRun) -> dict[str, Any]:
    values = {
        "adapter_id": model_run.adapter_id,
        "adapter_digest": model_run.adapter_digest,
        "normalized_output_digest": model_run.normalized_output_digest,
        "policy_version": model_run.policy_version,
        "issuer": model_run.issuer,
        "signer": model_run.signer,
        "model_license": model_run.model_license,
        "system_prompt_digest": model_run.system_prompt_digest,
        "retrieval_corpus_digest": model_run.retrieval_corpus_digest,
    }
    return {key: value for key, value in values.items() if value is not None}
