import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  static targets = ["file", "summary"]

  summarize() {
    const file = this.fileTarget.files[0]
    if (!file) {
      this.summaryTarget.value = "ink_receipts generates the commitment on submit"
      return
    }

    this.summaryTarget.value = `${file.name} · ${file.size} bytes · commitment generated by ink_receipts on submit`
  }
}
