source "https://rubygems.org"

gem "rails", "~> 7.1.5"
gem "sprockets-rails"
gem "sqlite3", "~> 1.4"
gem "puma", ">= 5.0"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "bootsnap", require: false
gem "rubyzip", "~> 2.3"
gem "ink_receipts", path: "gems/ink_receipts"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "dotenv-rails"
end

group :development do
  gem "web-console"
end
