class EvidenceItemsController < ApplicationController
  MAX_UPLOAD_BYTES = 10.megabytes

  def create
    @receipt = Receipt.find(params[:receipt_id])
    upload = params.dig(:evidence_item, :file)

    if upload.blank?
      redirect_to @receipt, alert: "Choose an evidence file before generating a commitment."
      return
    end

    if upload.size > MAX_UPLOAD_BYTES
      redirect_to @receipt, alert: "Evidence files are limited to 10 MB in this bootstrap."
      return
    end

    issued = InkReceipts.issue(
      payload: {
        name: params.dig(:evidence_item, :name).presence || upload.original_filename,
        evidence_type: params.dig(:evidence_item, :evidence_type).presence || "uploaded_record",
        source_system: params.dig(:evidence_item, :source_system).presence || "manual_upload",
        byte_size: upload.size,
        content_type: upload.content_type,
        retained: false
      },
      issuer: "Athian Evidence Explorer",
      receipt_type: "evidence_commitment",
      schema: "athian.evidence_commitment.v1",
      parents: [@receipt.body_digest].compact,
      lifecycle: "observed",
      avsa: @receipt.avsa.external_id,
      signer: "did:key:athian-evidence-demo",
      source_path: upload.tempfile.path
    )

    @receipt.evidence_items.create!(
      name: params.dig(:evidence_item, :name).presence || upload.original_filename,
      evidence_type: params.dig(:evidence_item, :evidence_type).presence || "uploaded_record",
      source_system: params.dig(:evidence_item, :source_system).presence || "manual_upload",
      commitment: issued.fetch(:body_digest),
      disclosure_status: params.dig(:evidence_item, :disclosure_status).presence || "restricted",
      required: ActiveModel::Type::Boolean.new.cast(params.dig(:evidence_item, :required)),
      status: "present",
      captured_at: Time.current,
      metadata: {
        filename: upload.original_filename,
        content_type: upload.content_type,
        byte_size: upload.size,
        retained: false
      }
    )

    redirect_to @receipt, notice: "Evidence commitment generated by ink_receipts. The source file was not retained."
  end
end
